# Configuration UI chatbot n8n
DEBUG_MODE=true
WEBHOOK_URL=http://15.236.66.128/n8n/webhook-test/54d38769-ae69-45db-80ad-3080d7ba9c68
# WEBHOOK_URL=http://15.236.66.128/n8n/webhook/chat-poc
ANIMATION=true
TYPEWRITER_SPEED_MS=2
